### ISSUE TITLE
If email is not registered as a user, send reset password link form reloads without an error message.

### ISSUE THREAD

**Issue by KrzysztofMadejski** [epforgpl/epf-sso#40]
Steps to reproduce:
1. Go to 
2. Enter your email
3. Clikc "Wyślij link do zmiany hasła"

Effect: website is reloaded, but there is no confirmation message. For the message two options:
1) email address doesn't exist / email was sent
2) if email address exists you should get an email with recovery link

**Comment by danielmacyszyn** [comment]
Fixed by @janzankowski
