### ISSUE TITLE
Unintuitional color design

### ISSUE THREAD

**Issue by KrzysztofMadejski** [epforgpl/epf-sso#42]
At https://sso.epf.org.pl/register-success at first glance I've read "Utworzono nowe konto" as "Utwórz nowe konto" and found it confusing. The good practice is to give a confirmation message a green background.

BTW: Why the need for https://sso.epf.org.pl/register-success page? You could redirect directly to login page (to test password) or instantly login user.

**Comment by janzankowski** [comment]
Fixed
